[project]
name = "app"
version = "0.1.0"
description = ""
authors = [
    {name = "wyhwong",email = "wyhwong@link.cuhk.edu.hk"}
]
license = "MIT"
readme = "README.md"
keywords = ["python"]
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
requires-python = ">=3.10,<4.0"

dependencies = [
    "tqdm (>=4.67.1,<5.0.0)",
    "cachetools (>=6.2.4,<7.0.0)",
    "tenacity (>=9.1.2,<10.0.0)",
]

[dependency-groups]
dev = [
    "pytest>=8.1.1",
    "pytest-asyncio>=0.23.3",
    "pytest-cov>=4.1.0",
    "pytest-env>=1.1.3",
    "mypy>=1.8.0",
    "pre-commit>=3.6.0",
    "ipykernel>=6.29.4",
]
mkdocs = [
    "mkdocs>=1.6.1, <2.0.0",
    "mkdocs-jupyter>=0.25.1",
    "mkdocs-mermaid2-plugin>=1.2.3",
]

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
include_trailing_comma = true
lines_after_imports = 2

[tool.bandit]
exclude_dirs = ["tests",]

[tool.mypy]
exclude = ["tests",]

[[tool.mypy.overrides]]
module = "*.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
env = [
    "STREAMING_LOG_LEVEL=30",
    "FILE_LOG_LEVEL=10",
    "LOG_FILEPATH=./test_report/runtime.log",
    "TZ=UTC",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
